baseURL: "https://blog.uier.tw/"
languageCode: "zh-tw"
title: uier
theme: PaperMod
paginate: 10

menu:
    main:
        - identifier: about
          name: ÈóúÊñºÊàë
          url: /about/
          weight: 10
        - identifier: archives
          name: ÊñáÁ´†ÂàóË°®
          url: /archives/
          weight: 20
        - identifier: categories
          name: ÊñáÁ´†ÂàÜÈ°û
          url: /categories/
          weight: 30
        - identifier: search
          name: ÊêúÂ∞ãÊñáÁ´†
          url: /search/
          weight: 40

params:
    homeInfoParams:
        Title: "Welcome to my blog. üëã"
        Content: >
            „Ñè„Ñè
    socialIcons:
        - name: email
          url: "mailto:ap9940506@gmail.com"
        - name: github
          url: "https://github.com/Uier"
        - name: "facebook"
          url: "https://facebook.com/TnUier"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary