baseURL: "https://blog.uier.tw/"
languageCode: "zh-tw"
title: uier
theme: PaperMod
paginate: 10

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 5
        - identifier: about
          name: About
          url: about/
          weight: 10
        - identifier: archives
          name: Archive
          url: archives/
          weight: 20
        - identifier: categories
          name: Categories
          url: categories/
          weight: 30
        - identifier: tags
          name: Tags
          url: tags/
          weight: 40
        - identifier: search
          name: Search
          url: search/
          weight: 50

params:
    homeInfoParams:
        Title: "歡迎光臨子緯的部落格"
        Content: >
            記錄一些學習的東西
    socialIcons:
        - name: email
          url: "mailto:ap9940506@gmail.com"
        - name: github
          url: "https://github.com/Uier"
        - name: "facebook"
          url: "https://facebook.com/TnUier"
        - name: "telegram"
          url: "https://t.me/TzuWei"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: "dracula"